{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.modules.niri;
  inherit (lib)
    mkIf
    mkEnableOption
    optionalString
    concatMapStringsSep
    removePrefix
    hasInfix
    splitString
    ;
  inherit (builtins)
    isAttrs
    toString
    match
    elemAt
    ;
  inherit (config.lib.stylix) colors;

  # Binary paths
  ghostty = "${pkgs.ghostty}/bin/ghostty";
  thunar = "${pkgs.thunar}/bin/thunar";
  fuzzel = "${pkgs.fuzzel}/bin/fuzzel";
  cliphist = "${pkgs.cliphist}/bin/cliphist";
  wl-copy = "${pkgs.wl-clipboard}/bin/wl-copy";
  brightnessctl = "${pkgs.brightnessctl}/bin/brightnessctl";
  playerctl = "${pkgs.playerctl}/bin/playerctl";

  # Reuse the hyprland monitor definitions (hosts set modules.hyprland.monitors)
  # and translate them to niri output blocks. Hyprland matches EDID monitors
  # with a "desc:" prefix; niri matches the same "make model serial" string
  # without it. String resolutions like "preferred"/"highres@highrr" have no
  # niri equivalent, so those outputs fall back to niri's automatic mode.
  mkOutput =
    m:
    let
      name = removePrefix "desc:" m.name;
      mode =
        if isAttrs m.resolution then
          "${toString m.resolution.width}x${toString m.resolution.height}@${toString m.resolution.refreshRate}"
        else if hasInfix "x" m.resolution then
          m.resolution
        else
          null;
      hasPos = match "-?[0-9]+x-?[0-9]+" m.position != null;
      posParts = splitString "x" m.position;
    in
    if m.enabled then
      ''
        output "${name}" {
            scale ${m.scale}
            ${optionalString (mode != null) ''mode "${mode}"''}
            ${optionalString hasPos "position x=${elemAt posParts 0} y=${elemAt posParts 1}"}
        }
      ''
    else
      ''
        output "${name}" {
            off
        }
      '';

  configKdl = ''
    // Generated by modules/hm/wms/niri — do not edit in place.
    // Keybind translation notes vs hyprland:
    //   Mod+F        = maximize column (floating toggle moved to Mod+T)
    //   Mod+R        = cycle preset column widths (screen record moved to Mod+Shift+R)
    //   Mod+G        = tabbed column display (closest analog to hyprland groups)
    //   Mod+U / Mod+I = workspace down/up (niri workspaces are vertical per output)
    //   Mod+Shift+Slash shows the full hotkey overlay.

    input {
        keyboard {
            xkb {
                layout "us"
                options "compose:caps"
            }
            repeat-delay 600
            repeat-rate 40
            numlock
        }
        touchpad {
            tap
            natural-scroll
            scroll-factor 0.4
        }
        focus-follows-mouse
    }

    ${concatMapStringsSep "\n" mkOutput config.modules.hyprland.monitors}

    layout {
        gaps 8
        focus-ring {
            width 2
            active-gradient from="#${colors.base0B}" to="#${colors.base0A}" angle=45
            inactive-color "#${colors.base00}"
        }
        border {
            off
        }
        default-column-width { proportion 0.5; }
        preset-column-widths {
            proportion 0.33333
            proportion 0.5
            proportion 0.66667
        }
    }

    cursor {
        xcursor-size 24
        hide-when-typing
    }

    environment {
        GDK_BACKEND "wayland,x11,*"
        QT_QPA_PLATFORM "wayland;xcb"
        QT_STYLE_OVERRIDE "kvantum"
        SDL_VIDEODRIVER "wayland"
        MOZ_ENABLE_WAYLAND "1"
        ELECTRON_OZONE_PLATFORM_HINT "wayland"
        OZONE_PLATFORM "wayland"
        XCOMPOSEFILE "~/.XCompose"
    }

    // niri spawns xwayland-satellite on demand and sets DISPLAY itself.
    xwayland-satellite {
        path "${pkgs.xwayland-satellite}/bin/xwayland-satellite"
    }

    prefer-no-csd
    screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"

    workspace "browser"
    workspace "chat"

    window-rule {
        match app-id=r#"^(org\.pulseaudio\.pavucontrol|\.blueman-manager-wrapped|hu\.irl\.cameractrls|nm-connection-editor|btop)$"#
        open-floating true
    }
    window-rule {
        match app-id="Slack"
        match app-id=r#".*gather.*"#
        open-on-workspace "chat"
    }

    spawn-at-startup "${pkgs.networkmanagerapplet}/bin/nm-applet" "--indicator"

    binds {
        Mod+Shift+Slash { show-hotkey-overlay; }

        // Applications
        Mod+Return { spawn "${ghostty}"; }
        Mod+Space { spawn "${fuzzel}"; }
        Mod+E { spawn "${thunar}"; }
        Mod+Y { spawn "oath" "19125157"; }
        Mod+V { spawn "sh" "-c" "${cliphist} list | ${fuzzel} --dmenu | ${cliphist} decode | ${wl-copy}"; }

        // Windows
        Mod+Q { close-window; }
        Mod+F { maximize-column; }
        Mod+Shift+F { fullscreen-window; }
        F11 { fullscreen-window; }
        Mod+T { toggle-window-floating; }
        Mod+O repeat=false { toggle-overview; }

        // Focus (vim + arrows)
        Mod+H { focus-column-left; }
        Mod+J { focus-window-down; }
        Mod+K { focus-window-up; }
        Mod+L { focus-column-right; }
        Mod+Left { focus-column-left; }
        Mod+Down { focus-window-down; }
        Mod+Up { focus-window-up; }
        Mod+Right { focus-column-right; }

        // Move
        Mod+Shift+H { move-column-left; }
        Mod+Shift+J { move-window-down; }
        Mod+Shift+K { move-window-up; }
        Mod+Shift+L { move-column-right; }
        Mod+Shift+Left { move-column-left; }
        Mod+Shift+Down { move-window-down; }
        Mod+Shift+Up { move-window-up; }
        Mod+Shift+Right { move-column-right; }

        // Column grouping (≈ hyprland groups; tabbed display ≈ group tabs)
        Mod+Comma { consume-window-into-column; }
        Mod+Period { expel-window-from-column; }
        Mod+G { toggle-column-tabbed-display; }

        // Resize
        Mod+R { switch-preset-column-width; }
        Mod+Minus { set-column-width "-10%"; }
        Mod+Equal { set-column-width "+10%"; }
        Mod+Shift+Minus { set-window-height "-10%"; }
        Mod+Shift+Equal { set-window-height "+10%"; }

        // Workspaces (vertical in niri)
        Mod+U { focus-workspace-down; }
        Mod+I { focus-workspace-up; }
        Mod+Ctrl+U { move-column-to-workspace-down; }
        Mod+Ctrl+I { move-column-to-workspace-up; }
        Mod+Tab { focus-workspace-previous; }
        Mod+B { focus-workspace "browser"; }
        Mod+C { focus-workspace "chat"; }
        Mod+1 { focus-workspace 1; }
        Mod+2 { focus-workspace 2; }
        Mod+3 { focus-workspace 3; }
        Mod+4 { focus-workspace 4; }
        Mod+5 { focus-workspace 5; }
        Mod+6 { focus-workspace 6; }
        Mod+7 { focus-workspace 7; }
        Mod+8 { focus-workspace 8; }
        Mod+9 { focus-workspace 9; }
        Mod+0 { focus-workspace 10; }
        Mod+Shift+1 { move-column-to-workspace 1; }
        Mod+Shift+2 { move-column-to-workspace 2; }
        Mod+Shift+3 { move-column-to-workspace 3; }
        Mod+Shift+4 { move-column-to-workspace 4; }
        Mod+Shift+5 { move-column-to-workspace 5; }
        Mod+Shift+6 { move-column-to-workspace 6; }
        Mod+Shift+7 { move-column-to-workspace 7; }
        Mod+Shift+8 { move-column-to-workspace 8; }
        Mod+Shift+9 { move-column-to-workspace 9; }
        Mod+Shift+0 { move-column-to-workspace 10; }

        // Monitors
        Mod+Shift+Alt+Left { move-column-to-monitor-left; }
        Mod+Shift+Alt+Right { move-column-to-monitor-right; }

        // Screenshots (niri built-in UI)
        Print { screenshot; }
        Mod+Print { screenshot-window; }
        Ctrl+Print { screenshot-screen; }

        // Screen recording
        Mod+Shift+R { spawn "wf-recorder-toggle"; }

        // Keyboard backlight
        Mod+F3 { spawn "sh" "-c" "${brightnessctl} -d *::kbd_backlight set +33%"; }
        Mod+F2 { spawn "sh" "-c" "${brightnessctl} -d *::kbd_backlight set 33%-"; }

        // Media keys
        XF86AudioRaiseVolume allow-when-locked=true { spawn "volume-action" "up"; }
        XF86AudioLowerVolume allow-when-locked=true { spawn "volume-action" "down"; }
        XF86AudioMute allow-when-locked=true { spawn "volume-action" "mute"; }
        XF86AudioMicMute allow-when-locked=true { spawn "mic-action" "mute"; }
        XF86MonBrightnessUp allow-when-locked=true { spawn "${brightnessctl}" "set" "5%+"; }
        XF86MonBrightnessDown allow-when-locked=true { spawn "${brightnessctl}" "set" "5%-"; }
        XF86AudioNext allow-when-locked=true { spawn "${playerctl}" "next"; }
        XF86AudioPause allow-when-locked=true { spawn "${playerctl}" "play-pause"; }
        XF86AudioPlay allow-when-locked=true { spawn "${playerctl}" "play-pause"; }
        XF86AudioPrev allow-when-locked=true { spawn "${playerctl}" "previous"; }

        // Lock / session
        Ctrl+Alt+Shift+L { spawn "loginctl" "lock-session"; }
        Mod+Shift+E { quit; }
    }
  '';

  # Fail the build (not the session) on config mistakes.
  validatedConfig =
    pkgs.runCommand "niri-config.kdl"
      {
        inherit configKdl;
        passAsFile = [ "configKdl" ];
        nativeBuildInputs = [ pkgs.niri ];
      }
      ''
        niri validate --config "$configKdlPath"
        install -m444 "$configKdlPath" "$out"
      '';
in
{
  options = {
    modules.niri.enable = mkEnableOption "Enable niri config (parallel session experiment)" // {
      default = true;
    };
  };
  config = mkIf cfg.enable {
    xdg.configFile."niri/config.kdl".source = validatedConfig;
  };
}
